config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # Router for fishtrip
  resources :fishtrip, only: [:show] do
    collection do
      resources :articles, controller: 'fishtrip/articles', only: [:show]
      get '/:country', to: 'fishtrip/country#index', country: /[a-zA-Z_]+/
      get '/:country/:city_en', to: 'fishtrip/country#city'
    end
  end

  # Router for booking
  resources :booking, only: [:show] do
    collection do
      resources :landmark, controller: 'booking/landmark', only: [:show]
      resources :airport, controller: 'booking/airport', only: [:show]
      get '/:country', to: 'booking/country#index', country: /[a-z]{2}/
      get '/:country/:city_unique', to: 'booking/country#city'
      get '/:country/:city_unique/review.html', to: 'booking/review#show'
    end
  end

  # Router for clock hotels
  resources :clockhotel, only: [:show] do
    collection do
      get '/:city_name_en', to: 'clockhotel#list', city_name_en: /[A-Za-z_]+/
    end
  end
end

app/controllers/booking/airport_controller.rb
class Booking::AirportController < ApplicationController
  def show
    @location = BookingAirport.find_by!(iata: params[:id].upcase)
    set_seo_elements('airport')
    render "show_#{@language}"
  end

  private

  def set_seo_elements(page_type)
    @seo = BookingSeo.new(@location, page_type, @language)
    @tdk = @seo.get_tdk
  end
end

app/controllers/booking/country_controller.rb
class Booking::CountryController < ApplicationController
  def index
    @cities = BookingCity.where("country_code=? and city_ranking>0", params[:country])
    @seo = BookingSeo.new(@cities, 'country', @language)
    @tdk = @seo.get_tdk
    render "index_#{@language}"
  end

  def city
    @location = BookingCity.includes(:airports).find_by!(country_code: params[:country], full_name: params[:city_unique])
    @hotels = @location.hotels.includes(:reviews).page(params[:page])
    @comments = BookingReview.find_comments(@hotels, @language)
    render "city_#{@language}.js.erb" and return if request.xhr?
    set_seo_elements('city')
    @landmarks = @seo.get_landmarks_with_city
    render "city_#{@language}"
  end

  private

  def set_seo_elements(page_type)
    @seo = BookingSeo.new(@location, page_type, @language)
    @tdk = @seo.get_tdk
  end
end

app/controllers/booking/landmark_controller.rb
class Booking::LandmarkController < ApplicationController
  def show
    @location = BookingLandmark.find(params[:id])
    hotel_ids = JSON.parse(@location.hotels)
    @hotels = BookingHotel.find_hotels_by_ids(hotel_ids)
    set_seo_elements('landmark')
    @comments = BookingReview.find_comments(@hotels, @language)
    render "show_#{@language}"
  end

  private

  def set_seo_elements(page_type)
    @seo = BookingSeo.new(@location, page_type, @language, @hotels.first)
    @tdk = @seo.get_tdk
  end
end

app/controllers/booking/review_controller.rb
class Booking::ReviewController < ApplicationController
  def show
    @location = BookingCity.includes(:airports).find_by!(country_code: params[:country], full_name: params[:city_unique])
    @hotels = @location.hotels.page(params[:page])
    set_seo_elements('review')
    @reviews = BookingReview.find_6_reviews(@hotels, @language)
    render "show_#{@language}"
  end

  private

  def set_seo_elements(page_type)
    @seo = BookingSeo.new(@location, page_type, @language)
    @tdk = @seo.get_tdk
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def show
    @hotel = BookingHotel.includes(:city).find(params[:id])
    redirect_to @hotel.shared_uri, status: 302 and return unless request.bot?
    @location = @hotel.city
    set_seo_elements('detail')
    @comments = BookingReview.find_comments_with_hotel(@hotel, @language)
    render "show_#{@language}"
  end

  private

  def set_seo_elements(page_type)
    @seo = BookingSeo.new(@location, page_type, @language, @hotel)
    @tdk = @seo.get_tdk
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_params
  before_action :find_city_by_full_name, only:['city_list_by_get','city_list_by_post', 'city_review']
  before_action :find_landmark_by_id, only: ['landmark'] 

  def country
    @cities = BookingCity.where("country_code=? and city_ranking>0", params[:country])
    render_404 if @cities.empty?
    @language = get_language
    @seo = BookingSeo.new(@cities,'country', @language)
    @tdk = @seo.get_tdk
    @breadcrumb = @seo.get_breadcrumb
    render "country_#{@language}"
  end

  def city_list_by_get
    @hotels = BookingHotel.search(@filter_args)
    set_seo_elements('city')
    @comments = BookingReview.find_comments(@hotels,@language)
    @landmarks = @seo.get_landmarks_with_city
    @airports = find_airports_in_city
    render "list_#{@language}"
  end

  def city_list_by_post
    @hotels = BookingHotel.search(@filter_args)
    @comments = {}
    @location = @city||@landmark||@airport
    @language = get_language
    render "list_#{@language}.js.erb"
  end

  def landmark
    hotel_ids = JSON.parse(@landmark.hotels)
    @hotels = BookingHotel.find_hotels_by_ids(hotel_ids)
    set_seo_elements('landmark')
    @comments = BookingReview.find_comments(@hotels, @language)
    render "landmark_#{@language}"
  end

  def airport
    @airport = BookingAirport.find_by(:iata=>params[:iata].upcase)
    render_404 unless @airport
    @hotels = JSON.parse(@airport.hotels)
    set_seo_elements('airport')
    render "airport_#{@language}"
  end

  def city_review
    @hotels = BookingHotel.search(@filter_args)
    set_seo_elements('review')
    @reviews = BookingReview.find_6_reviews(@hotels, @language)
    render "review_#{@language}"
  end

  def detail
    @hotel = BookingHotel.find_by(:id=>params[:id])
    render_404 unless @hotel
    redirect_to "#{@hotel.hotel_url}?aid=897435", :status=>302 and return unless @spider_tracked
    params[:country],params[:city_unique] = @hotel.cc1,@hotel.city_unique
    find_city_by_full_name
    set_seo_elements('detail')
    @comments = BookingReview.find_comments_with_hotel(@hotel, @language)
    @nearby_hotels = @hotel.get_nearby_hotels
    render "detail_#{@language}"
  end

  private

  def set_params
    @filter_args = params.permit(:city_unique, :page)
    @filter_args[:cc1] = params[:country]
  end

  def find_city_by_full_name
    @city = BookingCity.find_by(:country_code=>params[:country],:full_name=>params[:city_unique])
    render_404 unless @city
  end

  def find_landmark_by_id
    @landmark = BookingLandmark.find(params[:id])
    render_404 unless @landmark
  end

  def find_airports_in_city
    BookingAirport.airports(@city.full_name,@language)
  end

  def set_seo_elements(page_type)
    @page_type = page_type
    @location = @city||@landmark||@airport
    @language = get_language
    @seo = BookingSeo.new(@location, @page_type, @language, @hotel)
    @tdk = @seo.get_tdk
    @breadcrumb = @seo.get_breadcrumb
    @keywords = @seo.get_keywords
  end

  def get_language
=begin
    if params[:country]
      Constant::LANG_CN_CC.include?(params[:country]) ? "cn" : "en"
    elsif @page_type=='detail'
      Constant::LANG_CN_CC.include?(@hotel.cc1) ? "cn" : "en"
    else
      Constant::LANG_CN_CC.include?(@location.country_code) ? "cn" : "en"
    end
=end
    return 'cn'
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/booking/_comment.html.erb
<% if @comments and !@comments.empty? %>
  <div class="comments">
    <h3 class="head"> <%= @location.name_cn %>酒店点评</h3>
    <% @comments.each do |k, comment| %>
      <p class="hotel-comment"><%= k %>点评:<%= comment.good %></p>
    <% end %>
  </div>
<% end %>

app/views/booking/_footer_cn.html.erb
<footer class="footer">
  <div class='container seo-area'>
    <%= render 'booking/comment' unless params[:controller] == 'booking' %>
    <% if @seo.has_keywords? %>
      <div id="keywords" class="clearfix">
        <h3 class='head'><%= @location.name_cn %>热门搜索</h3>
        <ul>
          <% @seo.get_keywords.each do |keyword| %>
            <li><p class="keyword"><%= keyword %></p></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @location.is_a? BookingCity %>
      <% if @landmarks && !@landmarks.empty? %>
        <div id="landmarks" class="clearfix">
          <h3 class='head'><%= @location.name_cn %>热门地标</h3>
          <ul>
            <% @landmarks.each do |landmark| %>
              <li><p><a href="<%= landmark[:url] %>"><%= landmark[:text] %></a></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% unless @location.airports.empty? %>
        <div id="airports" class="clearfix">
          <h3 class='head'><%= @location.name_cn %>机场附近酒店</h3>
          <ul>
            <% @location.seo_airports.each do |airport| %>
              <li><p><a href="<%= airport[:url] %>"><%= airport[:text] %>附近酒店</a></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%# <%= render 'layouts/friendlinks' %>
      <div class="clearfix">
        <p class='pull-right'><a href="/booking/<%= @location.country_code %>/<%= @location.full_name %>/review.html"><%= @location.name_cn %>酒店评论</a></p>
      </div>
    <% end %>
  </div>
</footer>

app/views/booking/_footer_en.html.erb
<footer class="footer">
  <div class='container seo-area'>
    <% if @seo.has_keywords? %>
      <div id="keywords" class="clearfix">
        <h3 class='head'><%= @landmark.name %>热门搜索</h3>
        <ul>
          <% @seo.get_keywords.each do |keyword| %>
            <li><p class="keyword"><%= keyword %></p></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <% if @location.is_a? BookingCity %>
      <% if @landmarks && !@landmarks.empty? %>
        <div id="landmarks" class="clearfix">
          <h3 class='head'>Hot landmarks in <%= @location.name %></h3>
          <ul>
            <% @landmarks.each do |landmark| %>
              <li><p><a href="<%= landmark[:url] %>"><%= landmark[:text] %></a></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <% unless @location.airports.empty? %>
        <div id="airports" class="clearfix">
          <h3 class='head'>Airports in <%= @location.name %></h3>
          <ul>
            <% @location.seo_airports.each do |airport| %>
              <li><p><a href="<%= airport[:url] %>"><%= airport[:text] %></a></p></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="clearfix">
        <p class='pull-right'><a href="/booking/<%= @location.country_code %>/<%= @location.full_name %>/review.html">Hotel reviews in <%= @location.name %></a></p>
      </div>
    <% end %>
  </div>
</footer>

app/views/booking/_hotel_cn.html.erb
<div class="hotel-item clearfix" data-hotelid="<%= hotel.id %>">
  <div class="hotel-pic"> 
    <a href="<%= booking_path(hotel) %>/" target="_blank">
      <img class="hotel-img" src="<%= hotel.photo_url %>" alt="<%= @location.name_cn %>酒店图片_<%= hotel.name_cn %>">
    </a>
  </div>
  <div class="hotel-body">
    <p class="hotel-name">
    <a href="<%= booking_path(hotel) %>/" target="_blank"><%= hotel.name_cn.empty? ? hotel.name : hotel.name_cn %></a>
    </p>
    <p> 
    <% if hotel.star > 0 %>
      <% hotel.star.times { %><span class="glyphicon glyphicon-star star"></span><% } %>
    <% end %>
    </p>
    <p class="location"><strong><%="位置："%></strong><%= @location.name_cn %></p>
    <p class='address'><strong><%= "地址：" %></strong><%= hotel.address_cn.empty? ? hotel.address : hotel.address_cn %></p>
    <p class="hotel-desc hidden-xs"><%= "#{hotel.name_cn}简介：#{hotel.desc_cn.empty? ? hotel.desc_zh : hotel.desc_cn }" %></p>
    <% if @comments[hotel.id] %>
      <p class="hotel-comment hidden-xs">用户点评：<%= @comments[hotel.id] %></p>
    <% end %>
    <% if hotel.minrate.nil? %>
      <p class="booking"><a href="<%= booking_path(hotel) %>/" target="_blank" class="btn btn-primary btn-xs" role="button">查看详情</a> 
    <% else %>
      <p class="booking"> 
      <a class="btn btn-success pull-right" href="<%= booking_path(hotel) %>/" target="_blank">预订</a>
      <strong class="price"><%= hotel.minrate %></strong><span class="cy-code"><%= hotel.currencycode %></span>
      </p>
    <% end %>
  </div>
</div>

app/views/booking/_hotel_en.html.erb
<div class="hotel-item clearfix">
  <div class="hotel-pic"> 
    <a href="<%= booking_path(hotel) %>/" target="_blank">
      <img class="hotel-img" src="<%= hotel.photo_url %>" alt="Images of <%= @location.name %> hotels - <%= hotel.name %>">
    </a>
  </div>
  <div class="hotel-body">
    <p class="hotel-name">
    <a href="<%= booking_path(hotel) %>/" target="_blank"><%= hotel.name %></a>
    </p>
    <p> 
    <% if hotel.star > 0 %>
      <% hotel.star.times { %><span class="glyphicon glyphicon-star star"></span><% } %>
    <% end %>
    </p>
    <p class="location"><strong><%="location:"%></strong><%= @location.name %></p>
    <p class='address'><strong><%= "address:" %></strong><%= hotel.address %></p>
    <p class="hotel-desc hidden-xs">Introduction of <%= "#{hotel.name}: #{hotel.desc_en}" %></p>
    <% if @comments[hotel.id] %>
      <p class="hotel-comment hidden-xs">reviews:<%= @comments[hotel.id] %></p>
    <% end %>
    <% if hotel.minrate.nil? %>
      <p class="booking"><a href="<%= booking_path(hotel) %>/" target="_blank" class="btn btn-primary btn-xs" role="button">View detail</a> 
    <% else %>
      <p class="booking"> 
      <a class="btn btn-success pull-right" href="<%= booking_path(hotel) %>/" target="_blank">Select your room</a>
      <strong class="price"><%= hotel.minrate %></strong><span class="cy-code"><%= hotel.currencycode %></span>
      </p>
    <% end %>
  </div>
</div>

app/views/booking/_nearby_hotel.html.erb
<div class="nearby-hotels clearfix">
  <h3>附近酒店</h3>
  <% @hotel.get_nearby_hotels.each do |hotel| %>
    <div class="col-xs-6 col-sm-4 col-md-4 nearby-hotel">
      <div class="thumbnail">
        <a href="<%= booking_path(@hotel) %>/" target="_blank">
          <img src="<%= hotel.photo_url %>" alt="<%= hotel.name_cn %>图片">
        </a>
        <div class='caption'>
          <p class="hotel-name">
          <a href="<%= booking_path(@hotel) %>/" target="_blank"><%= hotel.name_cn %></a>
          </p>
          <p class='com-overview'>地址：<%= hotel.address_cn %></p>
          <p class='com-overview'><span class="dollor-sign"></span><strong class="price"><%= hotel.minrate %></strong><%= hotel.currencycode %> 起/晚
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/booking/show_cn.html.erb
<article class="container cus-padding">
  <div class="col-md-6 cus-padding" id="desc">
    <div class="thumbnail">
      <a href="<%= booking_path(@hotel) %>/">
        <img src="<%= @hotel.photo_url %>" alt="<%= "#{@hotel.name_cn}图片" %>">
      </a>
    </div>
    <div class="isr" >
      <h2 class="itr-head"><a href="<%= booking_path(@hotel) %>/"><%= @hotel.name_cn.empty? ? @hotel.name : @hotel.name_cn %></a>
        <span class="pull-right"><strong class="price"><%= @hotel.minrate %></strong> <%= @hotel.currencycode %></span>
      </h2>
      <p style="padding-left:10px;"><%= @hotel.desc_cn %></p>
      <div class="ratings">
        <p class="pull-right"><%= @hotel.review_score %>分</p>
        <p>
        <% if @hotel.review_score.nil? %>
          <% 5.times do %> <span class="glyphicon glyphicon-star-empty"></span> <% end %>
        <% else %>
          <% review_score=(@hotel.review_score/2).to_i+1 %>
          <% review_score.times { %><span class="glyphicon glyphicon-star"></span><% } %>
        <% end %>
        </p>
      </div>
    </div>
    <div class="sider-bar">
      <p>
      <a class="btn btn-info" href="<%= booking_path(@hotel) %>/">查看更多房型</a>
      <a class="btn btn-warning pull-right" href="<%= booking_path(@hotel) %>/">预订房间</a>
      </p>
    </div>
    <%= render 'nearby_hotel' %>
  </div>
  <div class="col-md-6 cus-padding" >
    <div class="comment">
      <h3 class="comment-title"><%= @hotel.name_cn.empty? ? @hotel.name : @hotel.name_cn %>点评</h3>
    </div>
    <hr>
    <% @comments.each do |comment| %>
      <div class="isr ratings">
        <% if comment.score.nil? %>
          <% 5.times do %> <span class="glyphicon glyphicon-star-empty"></span> <% end %>
        <% else %>
          <% comment_score = (comment.score.to_i/2).to_i %>
          <% comment_score.times { %>
            <span class="glyphicon glyphicon-star"></span>
          <% } %>
        <% end %>
        <%= comment.score %>分 <span class="author"><%= comment.author %></span>
        <span class="pull-right"><%= comment.comment_time %></span>
        <p class="content"><%= comment.good %> </p>
      </div>
    <% end %>
  </div>
  </div>
</article>
<%= render 'footer_cn' %>

app/views/booking/show_en.html.erb
<article class="container cus-padding">
  <div class="col-md-6 cus-padding" id="desc">
    <div class="thumbnail">
      <a href="<%= booking_path(@hotel) %>/">
        <img src="<%= @hotel.photo_url %>" alt="<%= "Image of #{@hotel.name}" %>">
      </a>
    </div>
    <div class="isr" >
      <h2 class="itr-head"><a href="<%= booking_path(@hotel) %>/"><%= @hotel.name %></a>
        <span class="price pull-right">￥<%= @hotel.minrate %></span>
      </h2>
      <p style="padding-left:10px;"><%= @hotel.desc_en %></p>
      <div class="ratings">
        <p class="pull-right"><%= @hotel.review_score %>分</p>
        <p>
        <% if @hotel.review_score.nil? %>
          <% 5.times do %> <span class="glyphicon glyphicon-star-empty"></span> <% end %>
        <% else %>
          <% review_score=(@hotel.review_score/2).to_i+1 %>
          <% review_score.times { %><span class="glyphicon glyphicon-star"></span><% } %>
        <% end %>
        </p>
      </div>
    </div>
    <div class="sider-bar">
      <p>
      <a class="btn btn-info" href="<%= booking_path(@hotel) %>/">Select your rooms</a>
      <a class="btn btn-warning pull-right" href="<%= booking_path(@hotel) %>/">View Detail</a>
      </p>
    </div>
  </div>
  <div class="col-md-6 cus-padding" >
    <div class="comment">
      <h3 class="comment-title">Newest Reviews for <%= @hotel.name %></h3>
    </div>
    <hr>
    <% @comments.each do |comment| %>
      <div class="isr ratings">
        <% if comment.score.nil? %>
          <% 5.times do %> <span class="glyphicon glyphicon-star-empty"></span> <% end %>
        <% else %>
          <% comment_score = (comment.score.to_i/2).to_i %>
          <% comment_score.times { %><span class="glyphicon glyphicon-star"></span><% } %>
        <% end %>
        <%= comment.score %> from <span class="author"><%= comment.author %></span>
        <span class="pull-right"><%= comment.comment_time %></span>
        <p class="content"><%= comment.good %> </p>
      </div>
    <% end %>
  </div>
  </div>
</article>
<%= render 'footer_en' %>